### ISSUE TITLE
Precommit testing fails due firebase determination

### ISSUE THREAD

**Issue by dev7ch** [14nrv/buefy-shop#19]
Hola @14nrv,

after upstream update the test almost runs fine, execept the firebase URL determination.

```sh

silvans-macbook-pro:buefy-shop silvan$ git commit -m "update from upstream and firebase deploy modifications"
 ✔ Running tasks for *.js
 ✔ Running tasks for *.vue
 FAIL  __tests__/components/Header.spec.js
  ● Test suite failed to run

    FIREBASE FATAL ERROR: Can't determine Firebase Database URL.  Be sure to include databaseURL option when calling firebase.initializeApp().



      at fatal (node_modules/@firebase/database/dist/index.node.cjs.js:335:11)
      at RepoManager.Object.<anonymous>.RepoManager.databaseFromApp (node_modules/@firebase/database/dist/index.node.cjs.js:14987:13)
      at Object.instance.INTERNAL.registerService.Reference [as database] (node_modules/@firebase/database/dist/index.node.cjs.js:15526:130)
      at FirebaseAppImpl.Object.<anonymous>.FirebaseAppImpl._getService (node_modules/@firebase/app/dist/index.cjs.js:134:66)
      at FirebaseAppImpl.(anonymous function) [as database] (node_modules/@firebase/app/dist/index.cjs.js:323:31)
      at Object.<anonymous> (plugins/firebase.js:24:22)
      at Object.<anonymous> (store/modules/product/actions.js:9:17)
      at Object.<anonymous> (store/modules/product/index.js:19:16)
      at Object.<anonymous> (__tests__/__mocks__/fakeStore.js:17:16)
      at Object.<anonymous> (__tests__/components/Header.spec.js:13:18)
````
If i see the `__tests__/__mocks__/products.json` i guess this should be the DB used by fakestore.js for testing, or?

**Comment by 14nrv** [comment]
Hi @dev7ch,

Try to add inside this test (Header.spec.js) :
 jest.mock('@/plugins/firebase', () => jest.fn())

If you take a look to all others tests for components you will find this line.
I will commit this fix soon.

**Comment by dev7ch** [comment]
thank you! i can confirm that `jest.mock('@/plugins/firebase', () => jest.fn())` in Header.spec.js solve it
